// leaderboardData.js
// Static restroom data for the leaderboard.
// In the future this would come from a database/API.

const leaderboardData = {
  restrooms: [
    {
      id: 'ctc-212',
      code: 'CTC-212',
      building: 'CTC',
      buildingName: 'PLDT Convergent Technologies Center',
      floor: 2,
      distance: 120,
      status: 'Available',
      amenities: ['Toilet Paper', 'Bidet', 'Air Conditioner', 'Soap'],
      rating: 5.0,
      reviewCount: 18,
    },
    {
      id: 'f-213',
      code: 'F-213',
      building: 'F',
      buildingName: 'Faura Hall',
      floor: 2,
      distance: 80,
      status: 'Available',
      amenities: ['Toilet Paper', 'Soap'],
      rating: 4.8,
      reviewCount: 12,
    },
    {
      id: 'k-101',
      code: 'K-101',
      building: 'K',
      buildingName: 'Kostka Hall',
      floor: 1,
      distance: 90,
      status: 'Available',
      amenities: ['Toilet Paper', 'Soap', 'Bidet'],
      rating: 4.6,
      reviewCount: 9,
    },
    {
      id: 'som-401',
      code: 'SOM-401',
      building: 'SOM',
      buildingName: 'John Gokongwei School of Management',
      floor: 4,
      distance: 500,
      status: 'Available',
      amenities: ['Bidet', 'Soap', 'Air Conditioner'],
      rating: 4.5,
      reviewCount: 7,
    },
    {
      id: 'ctc-305',
      code: 'CTC-305',
      building: 'CTC',
      buildingName: 'PLDT Convergent Technologies Center',
      floor: 3,
      distance: 230,
      status: 'Available',
      amenities: ['Toilet Paper', 'Soap', 'Air Conditioner'],
      rating: 4.2,
      reviewCount: 14,
    },
    {
      id: 'seca-102',
      code: 'SEC-A-102',
      building: 'SEC-A',
      buildingName: 'Science Education Complex A',
      floor: 1,
      distance: 420,
      status: 'Available',
      amenities: ['Toilet Paper', 'Bidet'],
      rating: 4.1,
      reviewCount: 5,
    },
    {
      id: 'f-312',
      code: 'F-312',
      building: 'F',
      buildingName: 'Faura Hall',
      floor: 3,
      distance: 200,
      status: 'Occupied',
      amenities: ['Toilet Paper', 'Air Conditioner'],
      rating: 4.0,
      reviewCount: 11,
    },
    {
      id: 'bel-201',
      code: 'BEL-201',
      building: 'BEL',
      buildingName: 'Bellarmine Hall',
      floor: 2,
      distance: 310,
      status: 'Available',
      amenities: ['Toilet Paper', 'Soap'],
      rating: 3.9,
      reviewCount: 8,
    },
    {
      id: 'ss-202',
      code: 'SS-202',
      building: 'SS',
      buildingName: 'Social Sciences Building',
      floor: 2,
      distance: 175,
      status: 'Closed',
      amenities: ['Toilet Paper', 'Bidet'],
      rating: 3.8,
      reviewCount: 6,
    },
    {
      id: 'lh-514',
      code: 'LH-514',
      building: 'LH',
      buildingName: 'Leong Hall',
      floor: 5,
      distance: 350,
      status: 'Available',
      amenities: ['Soap'],
      rating: 3.4,
      reviewCount: 4,
    },
    {
      id: 'g-301',
      code: 'G-301',
      building: 'G',
      buildingName: 'Gonzaga Hall',
      floor: 3,
      distance: 260,
      status: 'Occupied',
      amenities: ['Toilet Paper'],
      rating: 3.2,
      reviewCount: 3,
    },
    {
      id: 'b-101',
      code: 'B-101',
      building: 'B',
      buildingName: 'Berchmans Hall',
      floor: 1,
      distance: 50,
      status: 'Under Maintenance',
      amenities: ['Toilet Paper'],
      rating: 2.0,
      reviewCount: 2,
    },
  ],
}

export const BUILDINGS = [
  { code: 'B',     name: 'Berchmans Hall' },
  { code: 'BEL',   name: 'Bellarmine Hall' },
  { code: 'C',     name: 'Schmitt Hall' },
  { code: 'CTC',   name: 'PLDT Convergent Technologies Center' },
  { code: 'F',     name: 'Faura Hall' },
  { code: 'G',     name: 'Gonzaga Hall' },
  { code: 'K',     name: 'Kostka Hall' },
  { code: 'LH',    name: 'Leong Hall' },
  { code: 'SEC-A', name: 'Science Education Complex A' },
  { code: 'SEC-B', name: 'Science Education Complex B' },
  { code: 'SEC-C', name: 'Science Education Complex C' },
  { code: 'SOM',   name: 'John Gokongwei School of Management' },
  { code: 'SS',    name: 'Social Sciences Building' },
]

export const STATUSES = ['Available', 'Occupied', 'Under Maintenance', 'Closed']

export const AMENITY_LIST = ['Toilet Paper', 'Bidet', 'Air Conditioner', 'Soap']

export default leaderboardData
